#!/bin/bash

#
#   interface between vim-grammarous or vim-LanguageTool and yalafi.shell
#   - collect all options passed by editor, except --api
#   - languagetool-commandline.jar is a bit picky with repeated options
#

#   LT's base directory
#
ltdir=~/.vim/pack/bundle/start/vim-grammarous/misc/LanguageTool-4.7

#   comment out to use languagetool-commandline
#
use_server="--server my"

opts=x
lang=en-GB
while [ $# -gt 1 ]
do
    if [ X$1 == X-l ]
    then
        # languagetool-commandline does not like multiple language specs
        shift
        lang=$1
    elif [ X$1 == X-c ]
    then
        # languagetool-commandline does not like multiple encoding specs
        # (yalafi.shell already includes --encoding utf-8)
        shift
    elif [ X$1 != X--api ]
    then
        opts+="$1 "
    fi
    shift
done

python -m yalafi.shell $use_server --output xml --language $lang \
            --lt-directory $ltdir --lt-options "$opts" $1 2>/dev/null

